### ISSUE TITLE
get error of NoMethodError undefined method `[]' for nil:NilClass when use invite module

### ISSUE THREAD

**Issue by dleyanlin** [fozavci/viproy-voipkit#5]
[-] Auxiliary failed: NoMethodError undefined method `[]' for nil:NilClass
[-] Call stack:
[-]   /usr/share/metasploit-framework/modules/auxiliary/voip/viproy_sip_invite.rb:147:in`block (2 levels) in run'
[-]   /usr/share/metasploit-framework/modules/auxiliary/voip/viproy_sip_invite.rb:133:in `times'
[-]   /usr/share/metasploit-framework/modules/auxiliary/voip/viproy_sip_invite.rb:133:in`block in run'
[-]   /usr/share/metasploit-framework/modules/auxiliary/voip/viproy_sip_invite.rb:126:in `each'
[-]   /usr/share/metasploit-framework/modules/auxiliary/voip/viproy_sip_invite.rb:126:in`run'
[*] Auxiliary module execution completed

**Comment by HacKeD0x90** [comment]
did you succeed fixing this error?
